### ISSUE TITLE
Viz notes

### ISSUE THREAD

**Issue by sckott** [ropensci/taxview#5]
- add phylopic sil's - see #3 
- facet by taxonomic rank? e.g., 

```r
# facet by rank
x %>% <other ggplot2 code> %>% facet_rank(phylum)
# custom name vs. name OR rank vs. rank
x %>% <other ggplot2 code> %>% compare_ranks(phylum)
x %>% <other ggplot2 code> %>% compare_names(Helianthus, Quercus)
```

with each facet being a diff. phylum

-----

any other ideas for taxonomically based vizualizations ? @cboettig @zachary-foster 

p.s.. Zach, we can already leverage viz tools you have in metacoder I think or just point people to metacoder?

**Comment by zachary-foster** [comment]
Hi Scott, is this package an extension to ggplot2? I dont remember seeing it before.

> any other ideas for taxonomically based vizualizations ? 

Anything meant for hierarchal data has some potential. Here are a few:

* treemaps: https://github.com/mtennekes/treemap
* sunbursts: https://github.com/timelyportfolio/sunburstR

> Zach, we can already leverage viz tools you have in metacoder I think or just point people to metacoder?

the `metacoder` `heat_tree` function returns uses ggplot2, so probably. I am planning on rewriting it soon, so if there is any functionality that would be helpful, feel free to open an issue to request it. A benefit of using metacoder is that  `taxa` is already used there as inputs. 

Btw, I have plans to add phylopic images to metacoder trees as well

**Comment by sckott** [comment]
no, not a ggplot2 extension, just part of it will be viz. not sure where this is going yet, just exploring

thanks! @zachary-foster  i'll check these out

**Comment by cboettig** [comment]
Adding to the random notes: some nice tree visualizations in `ggraph` as well, includes treemaps and particularly the dendrogram layouts.   https://cran.r-project.org/web/packages/ggraph/vignettes/Layouts.html  Currently these don't include branch lengths, but could be a nice visualization for the rank-based trees we get from stuff like ncbi and itis.  @thomasp85 has done a really nice job in making these plots work pretty well with very large graphs; both in performance terms and in creating a readable / pleasing visual.  Might be very cool to combine with phylopic silhouettes....

**Comment by thomasp85** [comment]
Fwiw branch length will get supported in the next development cycle

**Comment by sckott** [comment]
thanks @cboettig and @thomasp85 

note to self to check out: https://cran.rstudio.com/web/packages/data.tree/
